config/routes.rb
Rails.application.routes.draw do
 
  get 'sessions/new'

  resources :users
  resources :posts do
  	resources :comments
  end
  resource :session

  root 'posts#index'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :comment_title, presence: true
  validates :comment_body, presence: true, length: { maximum: 500 }
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments, dependent: :destroy
	belongs_to :user

	validates :title, :body, presence: true

	def self.all_descending
		where("created_at <= ?", Time.now).order("created_at desc")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :posts

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6, allow_blank: true }

  def gravatar_id
  	Digest::MD5::hexdigest(email.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def require_signin
  	unless current_user
  		redirect_to signin_path, alert: "Please sign in first!"
  	end
  end

  def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def current_user?(user)
		current_user == user
	end

	def require_admin
		unless current_user_admin?
			redirect_to root_path, alert: "Unauthorized access!"
		end
	end

	def current_user_admin?
		current_user && current_user.admin?
	end

	helper_method :current_user
	helper_method :current_user?
	helper_method :current_user_admin?

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_post
	before_action :require_signin
	before_action :require_admin, only: [:destroy]

	def new
		@comment = @post.comments.new
	end

	def create
		@comment = @post.comments.new(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to @post, notice: "Comment suceessfully posted!"
		else
			render :new
	end

	def destroy
	end
end

private

	def set_post
		@post = Post.find(params[:post_id])
	end

	def comment_params
		params.require(:comment).permit(:comment_title, :comment_body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]

	def index
		@posts = Post.all_descending
	end

	def show
		set_post
	end

	def edit
		set_post
	end

	def update
		set_post
		if @post.update(post_params)
			redirect_to @post, notice: "Blog post successfully updated!"
		else
			render :edit
		end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			redirect_to @post, notice: "Blog post successfully created!"
		else
			render :new
		end
	end

	def destroy
		set_post
		@post.destroy
		flash[:alert] = "Blog post destroyed!"
		redirect_to posts_url
	end

private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		flash[:notice] = "Welcome back, #{user.name}!"
  		redirect_to user
  	else
  		flash.now[:warning] = "Invalid email and/or password"
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "You've signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:show, :edit, :update, :destroy]

	def show
		set_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "New user account successfully created!"
		else
			render 'new'
		end
	end

	def edit
		set_user
	end

	def update
		set_user
		if @user.update(user_params)
			redirect_to @user, notice: "User account successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		set_user
		@user.destroy
		session[:user_id] = nil
		redirect_to root_url, alert: "Account successfully deleted!"
	end

private

def set_user
	@user = User.find(params[:id])
end

def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

def require_correct_user
	set_user
	unless current_user == @user
		redirect_to root_path
	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def profile_image_for(user)
		url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
		image_tag(url, alt: user.name)
	end
end

app/views/comments/new.html.erb
<h1>Commenting on "<%= @post.title %>"</h1>

<%= form_for([@post, @comment]) do |f| %>
	<div>
		<p>
			<%= f.label :comment_title %><br/>
			<%= f.text_field :comment_title, autofocus: true %><br/>
		</p>
		<p>
			<%= f.label :comment_body %><br/>
			<%= f.text_area :comment_body, size: "80x10" %><br/>
		</p>
	</div>
	<p>
		<%= f.submit 'Post Comment', class:"btn btn-primary" %> <%= link_to 'Cancel', root_path, class:"btn btn-warning" %>
	</p>
<% end %>

app/views/layouts/_footer.html.erb
<p>Alex Harker, 2016</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">BATTLE OR PARADE</a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Sign out", session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
<!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>FosterBlog</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<header>
			<%= render 'layouts/navbar' %>
		</header>

		<div id="main-container" class="container">
			<div class="row">
				<div id="main-content" class="col-xs-9">
					
					<%= flash[:alert] %>
					<%= flash[:notice] %>
					<%= flash[:warning] %>

					<%= yield %>

				</div>
			</div>

			<footer>
				<%= render 'layouts/footer' %>
			</footer>
			
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %><br/>
	</p>
	<p>
		<%= f.label :body %><br/>
		<%= f.text_area :body, size: "80x10" %><br/>
	</p>
	<p>
		<%= f.submit class:"btn btn-primary" %> <%= link_to 'Cancel', root_path, class:"btn btn-warning" %>
	</p>
<% end %>

app/views/posts/_new_post_button.html.erb
<% if current_user_admin? %>
	<p><%= link_to 'New Post', new_post_path, class:"btn btn-success" %></p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing "<%= @post.title %>"</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'new_post_button' %>

<div class="post">
	<% @posts.each do |post| %>
		<h2 id="index-post-title">
			<%= link_to post.title, post %>
		</h2>
		<p>
			<small>
				<%= post.user.name %>
			</small>
		</p>
		<p class="date">
			<%= post.created_at.to_date.to_formatted_s(:long) %>
		</p>
		<p>
			<%= simple_format(truncate(post.body, { length: 300, separator: ' ' })) %>
		</p>
		<p>
			<%= pluralize(post.comments.count, "Comment") %>
		</p>
		<p>
			<%= link_to "View Post", post, class:"btn btn-primary" %>
		</p>
	<% end %>
</div>

<%= render 'new_post_button' %>

app/views/posts/new.html.erb
<h1>Create Blog Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2>
	<%= @post.title %>
</h2>
<p>
	<small>
		<%= @post.user.name %>
	</small>
</p>
<p class="date">
	<%= @post.created_at.to_date.to_formatted_s(:long) %>
</p>
<p>
	<%= simple_format(@post.body) %>
</p>

<p>
	<%= link_to 'All Posts', posts_path, class:"btn btn-primary" %>
	<% if current_user_admin? %> 
		<%= link_to 'Edit Post', edit_post_path(@post), class:"btn btn-warning" %> 
		<%= link_to 'Delete Post', post_path(@post), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
		<% end %>
</p>

<div id="comment">

	<h3>
		<%= pluralize(@post.comments.count, "Comment") %> - 
		<% if current_user %>
			<%= link_to "Add Comment", new_post_comment_path(@post) %>
		<% else %>
			<%= link_to "Sign in to add comment!", signin_path %>
		<% end %>
	</h3>

	<% @post.comments.each do |comment| %>
		<h4 id="comment-title">
			<%= comment.comment_title %>  
			<small>
				<%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %>
			</small>
			<% if current_user_admin? %>
				<small id="delete-comment">
					 - <%= link_to "Delete Comment", '#' %>
				</small>
			<% end %>
		</h4>
		<p><%= comment.comment_body %></p>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %><br/>
	</p>
	<p>
		<%= f.label :email %><br/>
		<%= f.email_field :email %><br/>
	</p>
	<p>
		<%= f.label :password %><br/>
		<%= f.password_field :password %><br/>
	</p>
	<p>
		<%= f.label :password_confirmation, "Confirm Password" %><br/>
		<%= f.password_field :password_confirmation %><br/>
	</p>
	<p>
		<% if @user.new_record? %>
			<%= f.submit "Create Account", class:"btn btn-primary" %> 
		<% else %>
			<%= f.submit "Edit Account", class:"btn btn-primary" %> 
		<% end %>
		<%= link_to 'Cancel', root_path, class:"btn btn-warning" %>
	</p>
<% end %>

app/views/users/edit.html.erb
<h2>Editing <%= @user.name %>'s Account</h2>

<%= render 'form' %>

app/views/users/new.html.erb
<h2>Create New User Account</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<p style="float:left;padding-right:1.5em;"><%= profile_image_for(@user) %></p>

<h2>
	<%= @user.name %>'s Profile 
	<%= link_to "Edit Account Information", edit_user_path, class:"btn btn-warning" %> 
	<%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure you want to permanently delete your account?" }, class:"btn btn-danger" %> 	
</h2>

<p>
	<%= @user.email %>
	<% if @user.posts.count >= 1 %>
		 - <%= pluralize(@user.posts.count, 'post') %> contributed
	<% end %>
</p>

<% if @user.comments.any? %>
	<h3 id="profile-comments-title"><u>Comments</u></h3>
		<% @user.comments.each do |comment| %>
			<h4 id="comment-title">
				<%= comment.comment_title %>  
				<small><%= time_ago_in_words(comment.created_at) %> ago on "<%= link_to comment.post.title, post_path %>"</small>
			</h4>
			<p>
				<%= comment.comment_body %>
			</p>
		<% end %>
<% end %>